CREATE DATABASE alumnos;

CREATE TABLE ALUMNO (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CEDULA VARCHAR(10) UNIQUE NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20)NOT NULL,
    INASISTENCIA INT NOT NULL,
    CALIFICACION INT NOT NULL
);

INSERT INTO ALUMNO (CEDULA,NOMBRE,APELLIDO,INASISTENCIA,CALIFICACION)
VALUES  ('65302314','NELSON','PEÑA',5,10),
        ('12345678', 'MARIA',    'GARCIA',   22,   9), 
        ('87654321', 'LUCAS',    'RODRIGUEZ', 8,   5),  
        ('11223344', 'SOFIA',    'MARTINEZ', 25,   4),  
        ('99887766', 'DIEGO',    'LOPEZ',     3,   8); 